name: AsureCore
version: 1.0
author: SaintQd
main: org.saintqd.asurecore.AsureCore
api-version: 26.2
depend: [AsureLib]
softdepend:
  - PlaceholderAPI
  - CMI
  - WorldGuard
  - LiteBans
  - LuckPerms
  - Nexo
  - MythicMobs
  - HMCCosmetics
permissions:
  asurecore.admin:
    description: Access to admin commands.
    default: op